#!/bin/bash
#$ -S /bin/bash
#$ -cwd
#$ -N embed_3.40.50.970_prostt5
#$ -l tmem=26G
#$ -l h_rt=1:00:00
#$ -l gpu=true
#$ -l h=bubba-213-1
#$ -j y

set -e

source /SAN/orengolab/functional-families/janu/contrasted-ff/.venv/bin/activate

export HF_HOME=/SAN/orengolab/functional-families/janu/.hf_cache
export TRANSFORMERS_CACHE=/SAN/orengolab/functional-families/janu/.hf_cache
export PYTHONUNBUFFERED=1

CUDA_VISIBLE_DEVICES=0 \
python /SAN/orengolab/functional-families/janu/contrasted-ff/scripts/embed-david.py \
  -i /SAN/orengolab/functional-families/janu/contrasted-ff/HUPs_data/3.40.50.970/sc_outputs/cluster_reps.fasta \
  -o /SAN/orengolab/functional-families/janu/contrasted-ff/HUPs_data/3.40.50.970/embeddings/ProstT5/sc_reps_prostt5.lmdb \
  --model Rostlab/ProstT5 \
  --split_char '!' \
  --id 0 \
  --per_protein 1 \
  --half 1 \
  --is_3Di 0 \
  --max_seq_len 1280 \
  --max_residues 12000 \
  --max_batch 128 \
  --map_size_gb 1 \
  --bucket_size 4000 \
  --commit_every 4000 \
  --sync_every_secs 600

python /SAN/orengolab/functional-families/janu/contrasted-ff/scripts/lmdb_to_pt.py \
  --lmdb_path /SAN/orengolab/functional-families/janu/contrasted-ff/HUPs_data/3.40.50.970/embeddings/ProstT5/sc_reps_prostt5.lmdb \
  --output /SAN/orengolab/functional-families/janu/contrasted-ff/HUPs_data/3.40.50.970/embeddings/ProstT5/sc_reps_prostt5.pt \
  --emb_dim 1024
