#!/bin/bash
#$ -S /bin/bash
#$ -cwd
#$ -N embed_funfams_deduped_esm2
#$ -l tmem=26G
#$ -l h_rt=12:0:0
#$ -l gpu=true
#$ -l h=bubba-213-2
#$ -j y

echo "========================================"
echo "Job started on host: $(hostname)"
echo "Start time: $(date)"
echo "========================================"

# Activate virtual environment
source /SAN/orengolab/functional-families/janu/contrasted-ff/.venv/bin/activate

# Sanity checks
echo "CUDA_VISIBLE_DEVICES=$CUDA_VISIBLE_DEVICES"
nvidia-smi
python - <<'EOF'
import torch
print("CUDA available:", torch.cuda.is_available())
print("CUDA device count:", torch.cuda.device_count())
EOF

export HF_HOME=/SAN/orengolab/functional-families/janu/.cache/huggingface

# Run embedding job
python embed-esm2.py \
  -i /SAN/orengolab/functional-families/janu/contrasted-ff/funfams_deduped_s100.fasta \
  -o /SAN/orengolab/functional-families/janu/contrasted-ff/funfams-deduped-esm2.lmdb \
  --model facebook/esm2_t33_650M_UR50D \
  --split_char '!' \
  --id 0 \
  --per_protein 1 \
  --half 1 \
  --max_seq_len 1022 \
  --max_residues 12000 \
  --max_batch 128 \
  --bucket_size 10000 \
  --commit_every 20000 \
  --map_size_gb 50 \
  --sync_every_secs 600

echo "========================================"
echo "Job finished at: $(date)"
echo "========================================"
